
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependecies    
      run: npm install
    - name: Start application in background mode
      run: npm run start &
    - name: Start unit tests  
      run: npm run test:unit
    - name: Display my SoftUni UserName
      run: echo "Konspirat0r" 

  ui_test:

    runs-on: ubuntu-latest
    needs: build_and_unit_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependecies    
      run: npm install
    - name: Install Playwright browsers  
      run: npx playwright install      
    - name: Start application in background mode
      run: npm run start &
    - name: Sleep for five seconds
      run: sleep 5  
    - name: Start UI test    
      run: npm run test:ui

  deploy_on_production:

    runs-on: ubuntu-latest
    needs: ui_test
    
    steps:
    - name: Deploy to production on Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.RENDER_TOKEN }}      